FROM python:3.12-slim

RUN apt-get update &&  rm -rf /var/lib/apt/lists/*
RUN python3 -m venv venv && source venv/bin/activate

RUN pip install -r requirements.txt

WORKDIR /app

COPY . .
#  Ваш код здесь #

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 